<?php

if (!file_exists('madeline.php')) {
    copy('https://phar.madelineproto.xyz/madeline.php', 'madeline.php');
}
include 'madeline.php';

$MadelineProto = new \danog\MadelineProto\API('session.madeline');
$MadelineProto->start();
$obhicon = array('01d'=>'☀','02d'=>'🌤','03d'=>'☁️','04d'=>'🌥','09d'=>'🌦','10d'=>'🌧','11d'=>'⛈','13d'=>'❄️','50d'=>'💨','01n'=>'🌙','02n'=>'☁️','03n'=>'☁️','04n'=>'🌩','09n'=>'🌧','10n'=>'🌧','11n'=>'⛈','13n'=>'❄️','50n'=>'💨');
$obh = json_decode(file_get_contents("https://api.openweathermap.org/data/2.5/weather?q=Toshkent,UZ&units=metric&appid=a9d86a9dc54f8caf39ac424735ffc2e6"),true);
$obhavo = $obh['main']['temp'];
$icon = $obh['weather'][0]['icon'];
$time = date("H:i",strtotime("3 hour"));
$kun = date("d.m.Y",strtotime("3 hour"));
$soat = date("H:i",strtotime("3 hour"));
$soat1 = date("H:i",strtotime("3 hour"));
$soat2 = date("H:i",strtotime("3 hour"));
$soat3 = date("H:i",strtotime("3 hour"));
$soat4 = date("H:i",strtotime("3 hour"));
$soat5 = date("H:i",strtotime("3 hour"));
$soat = str_replace('1', '❶', $soat);
$soat = str_replace('2', '❷', $soat);
$soat = str_replace('3', '❸', $soat);
$soat = str_replace('4', '❹', $soat);
$soat = str_replace('5', '❺', $soat);
$soat = str_replace('6', '❻', $soat);
$soat = str_replace('7', '❼', $soat);
$soat = str_replace('8', '❽', $soat);
$soat = str_replace('9', '❾', $soat);
$soat = str_replace('0', 'ⓞ', $soat);
$soat1 = str_replace('1', '①', $soat1);
$soat1 = str_replace('2', '②', $soat1);
$soat1 = str_replace('3', '③', $soat1);
$soat1 = str_replace('4', '④', $soat1);
$soat1 = str_replace('5', '⑤', $soat1);
$soat1 = str_replace('6', '⑥', $soat1);
$soat1 = str_replace('7', '⑦', $soat1);
$soat1 = str_replace('8', '⑧', $soat1);
$soat1 = str_replace('9', '⑨', $soat1);
$soat1 = str_replace('0', 'ⓞ', $soat1);
$soat2 = str_replace('1', '¹', $soat2);
$soat2 = str_replace('2', '²', $soat2);
$soat2 = str_replace('3', '³', $soat2);
$soat2 = str_replace('4', '⁴', $soat2);
$soat2 = str_replace('5', '⁵', $soat2);
$soat2 = str_replace('6', '⁶', $soat2);
$soat2 = str_replace('7', '⁷', $soat2);
$soat2 = str_replace('8', '⁸', $soat2);
$soat2 = str_replace('9', '⁹', $soat2);
$soat2 = str_replace('0', '⁰', $soat2);
$soat3 = str_replace('1', '❶', $soat3);
$soat3 = str_replace('2', '❷', $soat3);
$soat3 = str_replace('3', '❸', $soat3);
$soat3 = str_replace('4', '❹', $soat3);
$soat3 = str_replace('5', '❺', $soat3);
$soat3 = str_replace('6', '❻', $soat3);
$soat3 = str_replace('7', '❼', $soat3);
$soat3 = str_replace('8', '❽', $soat3);
$soat3 = str_replace('9', '❾', $soat3);
$soat3 = str_replace('0', 'ⓞ', $soat3);
$soat4 = str_replace('1', '𝟙', $soat4);
$soat4 = str_replace('2', '𝟚', $soat4);
$soat4 = str_replace('3', '𝟛', $soat4);
$soat4 = str_replace('4', '𝟜', $soat4);
$soat4 = str_replace('5', '𝟝', $soat4);
$soat4 = str_replace('6', '𝟞', $soat4);
$soat4 = str_replace('7', '𝟟', $soat4);
$soat4 = str_replace('8', '𝟠', $soat4);
$soat4 = str_replace('9', '𝟡', $soat4);
$soat4 = str_replace('0', '𝟘', $soat4);
$soat5 = str_replace('1', '⓵', $soat5);
$soat5 = str_replace('2', '⓶', $soat5);
$soat5 = str_replace('3', '⓷', $soat5);
$soat5 = str_replace('4', '⓸', $soat5);
$soat5 = str_replace('5', '⓹', $soat5);
$soat5 = str_replace('6', '⓺', $soat5);
$soat5 = str_replace('7', '⓻', $soat5);
$soat5 = str_replace('8', '⓼', $soat5);
$soat5 = str_replace('9', '⓽', $soat5);
$soat5 = str_replace('0', 'ⓞ', $soat5);
$randomlist = ["$soat","$soat1","$soat2","$soat3","$soat4","$soat5"];
$random1 = array_rand($randomlist);
$random = "$randomlist[$random1]";
$nik = ["api_api | ⏰$random 😎"];
$nikrand = array_rand($nik);
$niktxt = "$nik[$nikrand]";
$bio = ["📆$kun | ⏰$time | $obhicon[$icon] $obhavo °C"];
$biorand = array_rand($bio);
$biotxt = "$bio[$biorand]";
$MadelineProto->account->updateProfile(['first_name'=>"$niktxt",'about'=>"$biotxt"]);
$MadelineProto->account->updateStatus(['offline' => false, ]);
unlink("MadelineProto.log");
?>